<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2P7KUM1" failures="6" tests="14" name="PetTests" time="37.02" errors="0" timestamp="2024-09-19T14:55:29 IST">
  <testcase classname="api.test.UserTests" name="testPostUser" time="6.066"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.602">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.UserTests.testGetUserByName(UserTests.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="2.18">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.UserTests.testUpdateUserByName(UserTests.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUserByName -->
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.358">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.UserTests.testDeleteUserByName(UserTests.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.UserTests2" name="testPostUser" time="2.121"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.536"/>
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="3.116"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.53"/>
  <testcase classname="api.test.UserDDTest" name="testPostuser" time="1.721"/>
  <testcase classname="api.test.UserDDTest" name="testPostuser" time="2.384"/>
  <testcase classname="api.test.UserDDTest" name="testPostuser" time="1.986"/>
  <testcase classname="api.test.UserDDTest" name="testDeleteUserByName" time="2.286">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.UserDDTest.testDeleteUserByName(UserDDTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.UserDDTest" name="testDeleteUserByName" time="1.981">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.UserDDTest.testDeleteUserByName(UserDDTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.UserDDTest" name="testDeleteUserByName" time="1.838">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at api.test.UserDDTest.testDeleteUserByName(UserDDTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- PetTests -->
